core23_facebook_success:
    path:   /auth/success
    defaults:  { _controller: 'core23_facebook.action.auth_success' }

core23_facebook_error:
    path:   /auth/error
    defaults:  { _controller: 'core23_facebook.action.auth_error' }

core23_facebook_check:
    path:   /auth/_check
    defaults:  { _controller: 'core23_facebook.action.check_auth' }

core23_facebook_auth:
    path:   /auth
    defaults:  { _controller: 'core23_facebook.action.start_auth' }
